apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simply-dashed.fullname" . }}
  labels:
    {{- include "simply-dashed.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
