apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simply-dashed.fullname" . }}
  labels:
    {{- include "simply-dashed.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "simply-dashed.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simply-dashed.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include "simply-dashed.configChecksum" . }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "simply-dashed.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            - -config
            - /app/config/config.yaml
            - -icon-dir
            - /app/data/icons
            - -refresh-icons=false
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.probes.startup | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
            # We provide an emptyDir volume for icons
            - name: data
              mountPath: /app/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "simply-dashed.selectorLabels" . | nindent 20 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        {{- range .Values.topologySpreadConstraints }}
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey }}
          whenUnsatisfiable: {{ .whenUnsatisfiable }}
          labelSelector:
            {{- if .labelSelector }}
            {{- toYaml .labelSelector | nindent 12 }}
            {{- else }}
            matchLabels:
              {{- include "simply-dashed.selectorLabels" $ | nindent 14 }}
            {{- end }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "simply-dashed.fullname" . }}
        - name: tmp
          emptyDir: {}
        - name: data
          emptyDir: {}

