{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "simply-dashed.fullname" . }}
  labels:
    {{- include "simply-dashed.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "simply-dashed.selectorLabels" . | nindent 6 }}
{{- end }}
